name: Project

on:
 pull_request:
   branches: ["*"]

jobs:
  Project:
   runs-on: ubuntu-latest
   steps:
     - env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: |
          export body=$(curl 'https://api.open-meteo.com/v1/forecast?latitude=52.5199&longitude=13.41&current_weather=true')
          export temperature=$(echo $body | jq '.current_weather.temperature')
          gh pr comment $PR_NUMBER --body "the temperature in Riyadh is $temperature" --repo $GITHUB_REPOSITORY 